// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type pktzConnKey struct {
	_     structs.HostLayout
	Pid   uint32
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Proto uint8
	Pad   [3]uint8
}

type pktzConnStats struct {
	_         structs.HostLayout
	TxBytes   uint64
	RxBytes   uint64
	TxPackets uint64
	RxPackets uint64
	LastNs    uint64
	Comm      [16]int8
}

type pktzProcStats struct {
	_         structs.HostLayout
	TxBytes   uint64
	RxBytes   uint64
	TxPackets uint64
	RxPackets uint64
	LastNs    uint64
	Comm      [16]int8
}

// loadPktz returns the embedded CollectionSpec for pktz.
func loadPktz() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PktzBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pktz: %w", err)
	}

	return spec, err
}

// loadPktzObjects loads pktz and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pktzObjects
//	*pktzPrograms
//	*pktzMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPktzObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPktz()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pktzSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pktzSpecs struct {
	pktzProgramSpecs
	pktzMapSpecs
	pktzVariableSpecs
}

// pktzProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pktzProgramSpecs struct {
	KprobeSkbConsumeUdp  *ebpf.ProgramSpec `ebpf:"kprobe_skb_consume_udp"`
	KprobeTcpCleanupRbuf *ebpf.ProgramSpec `ebpf:"kprobe_tcp_cleanup_rbuf"`
	KprobeTcpSendmsg     *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	KprobeUdpSendmsg     *ebpf.ProgramSpec `ebpf:"kprobe_udp_sendmsg"`
}

// pktzMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pktzMapSpecs struct {
	ConnStatsMap *ebpf.MapSpec `ebpf:"conn_stats_map"`
	ProcStatsMap *ebpf.MapSpec `ebpf:"proc_stats_map"`
}

// pktzVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pktzVariableSpecs struct {
}

// pktzObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPktzObjects or ebpf.CollectionSpec.LoadAndAssign.
type pktzObjects struct {
	pktzPrograms
	pktzMaps
	pktzVariables
}

func (o *pktzObjects) Close() error {
	return _PktzClose(
		&o.pktzPrograms,
		&o.pktzMaps,
	)
}

// pktzMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPktzObjects or ebpf.CollectionSpec.LoadAndAssign.
type pktzMaps struct {
	ConnStatsMap *ebpf.Map `ebpf:"conn_stats_map"`
	ProcStatsMap *ebpf.Map `ebpf:"proc_stats_map"`
}

func (m *pktzMaps) Close() error {
	return _PktzClose(
		m.ConnStatsMap,
		m.ProcStatsMap,
	)
}

// pktzVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPktzObjects or ebpf.CollectionSpec.LoadAndAssign.
type pktzVariables struct {
}

// pktzPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPktzObjects or ebpf.CollectionSpec.LoadAndAssign.
type pktzPrograms struct {
	KprobeSkbConsumeUdp  *ebpf.Program `ebpf:"kprobe_skb_consume_udp"`
	KprobeTcpCleanupRbuf *ebpf.Program `ebpf:"kprobe_tcp_cleanup_rbuf"`
	KprobeTcpSendmsg     *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	KprobeUdpSendmsg     *ebpf.Program `ebpf:"kprobe_udp_sendmsg"`
}

func (p *pktzPrograms) Close() error {
	return _PktzClose(
		p.KprobeSkbConsumeUdp,
		p.KprobeTcpCleanupRbuf,
		p.KprobeTcpSendmsg,
		p.KprobeUdpSendmsg,
	)
}

func _PktzClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pktz_bpfel.o
var _PktzBytes []byte
