// Package demo provides real-time anonymization of network data for safe
// screen-sharing and presentations. All mappings are ephemeral (session-only)
// and deterministic within a session (same real IP always → same fake IP).
package demo

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"math"
	"net"
	"sync"
	"time"

	"github.com/immanuwell/pktz/internal/collector"
)

var commonPorts = []uint16{80, 443, 8080, 8443, 5228, 1935, 3478, 53}

// Anonymizer replaces real IPs with consistent fake public IPs and can inject
// synthetic processes for demonstration purposes.
type Anonymizer struct {
	salt []byte

	mu      sync.Mutex
	ipMap   map[string]net.IP // real IP → fake IP (stable within session)
	hostMap map[string]string // fake IP string → plausible fake hostname

	fakeProcs []fakeProc
}

type fakeProc struct {
	name    string
	pid     uint32
	conns   []collector.ConnInfo
	rxBase  float64 // peak RX bytes/sec
	txBase  float64 // peak TX bytes/sec
	rxPhase float64
	txPhase float64
	period  float64 // oscillation period in seconds
}

// New creates an Anonymizer. fakeProcNames is an optional list of process names
// to inject into the process list (may be nil).
func New(fakeProcNames []string) (*Anonymizer, error) {
	salt := make([]byte, 16)
	if _, err := rand.Read(salt); err != nil {
		return nil, fmt.Errorf("generate salt: %w", err)
	}
	a := &Anonymizer{
		salt:    salt,
		ipMap:   make(map[string]net.IP),
		hostMap: make(map[string]string),
	}
	for _, name := range fakeProcNames {
		a.fakeProcs = append(a.fakeProcs, a.buildFakeProc(name))
	}
	return a, nil
}

// Processes anonymizes src/dst IPs (no-op on proc fields) and appends fake processes.
func (a *Anonymizer) Processes(procs []collector.ProcessInfo) []collector.ProcessInfo {
	out := make([]collector.ProcessInfo, len(procs))
	copy(out, procs)
	now := time.Now()
	t := float64(now.UnixNano()) / 1e9
	for _, fp := range a.fakeProcs {
		rx := fp.rxBase * math.Abs(math.Sin(t/fp.period+fp.rxPhase))
		tx := fp.txBase * math.Abs(math.Sin(t/fp.period+fp.txPhase))
		// accumulate totals from an imaginary start 10 minutes ago
		origin := t - 600
		out = append(out, collector.ProcessInfo{
			PID:       fp.pid,
			Comm:      fp.name,
			RxRate:    rx,
			TxRate:    tx,
			RxTotal:   uint64(fp.rxBase * 0.5 * (t - origin)),
			TxTotal:   uint64(fp.txBase * 0.5 * (t - origin)),
			ConnCount: len(fp.conns),
		})
	}
	return out
}

// Conns replaces SrcAddr and DstAddr in every ConnInfo with stable fake IPs.
func (a *Anonymizer) Conns(conns []collector.ConnInfo) []collector.ConnInfo {
	out := make([]collector.ConnInfo, len(conns))
	for i, c := range conns {
		c.SrcAddr = a.IPFor(c.SrcAddr)
		c.DstAddr = a.IPFor(c.DstAddr)
		out[i] = c
	}
	return out
}

// FakeConns returns the pre-generated connections for a fake process PID,
// or nil if pid does not belong to any injected fake process.
func (a *Anonymizer) FakeConns(pid uint32) []collector.ConnInfo {
	for _, fp := range a.fakeProcs {
		if fp.pid == pid {
			return fp.conns
		}
	}
	return nil
}

// IsFakePID reports whether pid was generated by an injected fake process.
func (a *Anonymizer) IsFakePID(pid uint32) bool {
	for _, fp := range a.fakeProcs {
		if fp.pid == pid {
			return true
		}
	}
	return false
}

// IPFor returns a stable fake public IP for the given real IP.
// Unspecified addresses are returned as-is.
func (a *Anonymizer) IPFor(real net.IP) net.IP {
	if real == nil || real.IsUnspecified() {
		return real
	}
	key := real.String()
	a.mu.Lock()
	defer a.mu.Unlock()
	if fake, ok := a.ipMap[key]; ok {
		return fake
	}
	var fake net.IP
	if v4 := real.To4(); v4 != nil {
		fake = a.genIPv4(v4)
	} else {
		fake = a.genIPv6(real.To16())
	}
	a.ipMap[key] = fake
	a.hostMap[fake.String()] = a.genHostname(fake)
	return fake
}

// HostnameFor returns the pre-generated fake hostname for a fake IP.
// Returns "", false if ip is not a known fake IP.
func (a *Anonymizer) HostnameFor(ip net.IP) (string, bool) {
	if ip == nil {
		return "", false
	}
	a.mu.Lock()
	defer a.mu.Unlock()
	h, ok := a.hostMap[ip.String()]
	return h, ok
}

// ── private helpers ───────────────────────────────────────────────────────────

func (a *Anonymizer) digest(data []byte) []byte {
	h := hmac.New(sha256.New, a.salt)
	h.Write(data)
	return h.Sum(nil)
}

func (a *Anonymizer) genIPv4(v4 []byte) net.IP {
	sum := a.digest(v4)
	for {
		ip := net.IP{sum[0], sum[1], sum[2], sum[3]}
		if !reservedV4(ip) {
			return ip
		}
		sum = a.digest(sum) // rehash until we land in a routable range
	}
}

func (a *Anonymizer) genIPv6(v6 []byte) net.IP {
	sum := a.digest(v6)
	ip := make(net.IP, 16)
	copy(ip, sum[:16])
	ip[0] = 0x26 // 2600::/7 — global unicast
	ip[1] &= 0x0f
	return ip
}

func (a *Anonymizer) genHostname(ip net.IP) string {
	v4 := ip.To4()
	if v4 == nil {
		sum := a.digest(ip)
		return fmt.Sprintf("node-%x.ipv6.example.net", sum[:4])
	}
	sum := a.digest(v4)
	switch int(sum[4]) % 5 {
	case 0:
		return fmt.Sprintf("ec2-%d-%d-%d-%d.eu-west-1.compute.amazonaws.com", v4[0], v4[1], v4[2], v4[3])
	case 1:
		return fmt.Sprintf("server-%d-%d-%d-%d.fra1.digitaloceanspaces.com", v4[0], v4[1], v4[2], v4[3])
	case 2:
		return fmt.Sprintf("%d.%d.%d.%d.bc.googleusercontent.com", v4[3], v4[2], v4[1], v4[0])
	case 3:
		return fmt.Sprintf("lb-%d-%d-%d-%d.cloudflare.com", v4[0], v4[1], v4[2], v4[3])
	default:
		return fmt.Sprintf("a%d%d.cdn%d.cloudfront.net", v4[0], v4[1], int(sum[5])%100)
	}
}

func (a *Anonymizer) buildFakeProc(name string) fakeProc {
	seed := a.digest([]byte(name))

	pid := uint32(binary.LittleEndian.Uint16(seed[0:2])) + 10000
	rxBase := float64(binary.LittleEndian.Uint32(seed[4:8]))/math.MaxUint32*8_000_000
	txBase := float64(binary.LittleEndian.Uint32(seed[8:12]))/math.MaxUint32*2_000_000
	period := 8.0 + float64(seed[12]%20)
	rxPhase := float64(seed[13]) / 255.0 * math.Pi * 2
	txPhase := float64(seed[14]) / 255.0 * math.Pi * 2

	numConns := int(seed[15]%3) + 2
	localIP := a.genIPv4([]byte{10, seed[16], seed[17], 1})
	// Store local fake IP in maps so it has a hostname too
	a.ipMap[localIP.String()] = localIP
	a.hostMap[localIP.String()] = fmt.Sprintf("laptop-%x.local", seed[16:18])

	conns := make([]collector.ConnInfo, numConns)
	for i := range conns {
		cseed := a.digest(append(seed, byte(i)))
		dst := a.genIPv4(cseed[:4])
		a.ipMap[dst.String()] = dst
		a.hostMap[dst.String()] = a.genHostname(dst)
		conns[i] = collector.ConnInfo{
			SrcAddr: localIP,
			SrcPort: 30000 + uint16(cseed[5])*100 + uint16(i),
			DstAddr: dst,
			DstPort: commonPorts[int(cseed[4])%len(commonPorts)],
			Proto:   "TCP",
			State:   "ESTABLISHED",
		}
	}

	return fakeProc{
		name:    name,
		pid:     pid,
		conns:   conns,
		rxBase:  rxBase,
		txBase:  txBase,
		rxPhase: rxPhase,
		txPhase: txPhase,
		period:  period,
	}
}

// reservedV4 returns true if ip should not appear as a routable public address.
func reservedV4(ip net.IP) bool {
	switch {
	case ip[0] == 0, ip[0] == 10, ip[0] == 127, ip[0] >= 224:
		return true
	case ip[0] == 100 && ip[1]&0xC0 == 64: // 100.64.0.0/10
		return true
	case ip[0] == 169 && ip[1] == 254: // 169.254.0.0/16
		return true
	case ip[0] == 172 && ip[1]&0xF0 == 16: // 172.16.0.0/12
		return true
	case ip[0] == 192 && ip[1] == 0: // 192.0.0.0/24, TEST-NET-1
		return true
	case ip[0] == 192 && ip[1] == 168: // 192.168.0.0/16
		return true
	case ip[0] == 198 && (ip[1] == 18 || ip[1] == 19 || ip[1] == 51): // 198.18/15, TEST-NET-2
		return true
	case ip[0] == 203 && ip[1] == 0 && ip[2] == 113: // TEST-NET-3
		return true
	}
	return false
}
